name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Site generation script
        run: node index.js generate

      - name: List generated files
        run: ls -la output

      - name: Upload generated HTML and CSS
        uses: actions/upload-artifact@v3
        with:
          name: generated-html
          path: output/*

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Download generated HTML and CSS
        uses: actions/download-artifact@v3
        with:
          name: generated-html

      - name: Prepare publish directory
        run: |
          mkdir -p publish
          mv output/* publish/ || true
          echo "Files moved to publish directory:"
          ls -la publish

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          publish_branch: gh-pages
